// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveUser() {
  return window['go']['main']['App']['GetActiveUser']();
}

export function GetAnimeDetails(arg1) {
  return window['go']['main']['App']['GetAnimeDetails'](arg1);
}

export function GetAnimeRanking(arg1) {
  return window['go']['main']['App']['GetAnimeRanking'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetLibraryByStatus(arg1) {
  return window['go']['main']['App']['GetLibraryByStatus'](arg1);
}

export function GetSeasonalAnime(arg1, arg2) {
  return window['go']['main']['App']['GetSeasonalAnime'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveAnimeFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveAnimeFromLibrary'](arg1);
}

export function SearchAnime(arg1, arg2) {
  return window['go']['main']['App']['SearchAnime'](arg1, arg2);
}

export function SearchManga(arg1, arg2) {
  return window['go']['main']['App']['SearchManga'](arg1, arg2);
}

export function SetMALClientID(arg1) {
  return window['go']['main']['App']['SetMALClientID'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdateAnimeStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAnimeStatus'](arg1, arg2, arg3, arg4);
}
