// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveUser():Promise<string>;

export function GetAnimeDetails(arg1:number):Promise<string>;

export function GetAnimeRanking(arg1:string):Promise<string>;

export function GetLibrary():Promise<string>;

export function GetLibraryByStatus(arg1:string):Promise<string>;

export function GetSeasonalAnime(arg1:number,arg2:string):Promise<string>;

export function GetSettings():Promise<string>;

export function Login():Promise<string>;

export function Logout():Promise<string>;

export function RemoveAnimeFromLibrary(arg1:number):Promise<string>;

export function SearchAnime(arg1:string,arg2:number):Promise<string>;

export function SearchManga(arg1:string,arg2:number):Promise<string>;

export function SetMALClientID(arg1:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<string>;

export function UpdateAnimeStatus(arg1:number,arg2:string,arg3:number,arg4:number):Promise<string>;
